#!/user/bin/env groovy
@Library('jenkins-shared-library-node') _

pipeline {
    agent any
    tools {
        nodejs "my-nodejs"
    }
    stages {
        stage('Increment Version') {
            steps {
                script {
                    def version = incrementVersion(appDir: 'app', releaseType: 'minor')
                    env.IMAGE_NAME = "${version}-${env.BUILD_NUMBER}"
                }
            }
        }
        stage('Run Tests') {
            steps {
                runTests(appDir: 'app')
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                buildAndPushDockerImage(
                    appDir: 'app',
                    imageName: "dm1984/demo-app:${env.IMAGE_NAME}",
                    credentialsId: 'dockerhub'
                )
            }
        }
        stage('Commit Version Update') {
            steps {
                commitVersionUpdate(
                    gitCredentialsId: 'github-jenkins',
                    repoUrl: 'github.com/aydamacink/twn_module_8_jenkins_exercises.git'
                )
            }
        }
    }
}
